### ISSUE TITLE
Add ideas for android apps

### ISSUE THREAD

**Issue by anshulkhattar** [anshulkhattar/Beginner-Level-Android-Studio-Apps#41]
Add your idea in the following format:

"Name - idea"

Eg.- "Anshul-Gallery App"

**Comment by Mcustis** [comment]
Martha-Closet App

**Comment by anshulkhattar** [comment]
Add this to ideas.md file and commit the changes.

**Comment by krnblni** [comment]
Karan - Intruder App

**Comment by anshulkhattar** [comment]
> Karan - Intruder App

Commit your ideas to ideas.md file. Don't write in the comments.

**Comment by git-ash22** [comment]
Akash - IncignitoBook
